[server]
local_ip = "127.0.0.1"
local_port = 3000
# only support second and  types.
timeout = 30
# "" => output to Stdout
# "xxx" => output to xxx file
log_file_name = ""
# 0 => Trace
# 1 => Debug
# 2 => Warn
# 3 => Info
# 4 => Error
log_level = 2

[token]
secret = "hell, rust"
# support second, min, hour and day types.
expire = "100d"

# [db]
# connect = ""
# db_name = ""
# username = ""
# password = ""

# [node]
# btc = {
#     devnet = [
#         { name = "publicnode", url = "" }
#     ],
#     testnet = [
#         { name = "publicnode", url = "" }
#     ],
#     mainnet = [
#         { name = "publicnode", url = "" }
#     ]
# }
# eth = {
#     devnet = [
#         { name = "publicnode", url = "" }
#     ],
#     testnet = [
#         { name = "publicnode", url = "" }
#     ],
#     mainnet = [
#         { name = "publicnode", url = "" }
#     ]
# }
