[server]
local_ip = "127.0.0.1"
local_port = 3000
# only support second and  types.
timeout = 30
# "" => output to Stdout
# "xxx" => output to xxx file
log_file_name = ""
# 0 => Trace
# 1 => Debug
# 2 => Warn
# 3 => Info
# 4 => Error
log_level = 2

[token]
secret = "hell, rust"
# support second, min, hour and day types.
expire = "100d"

# [db]
# connect = ""
# db_name = ""
# username = ""
# password = ""

[node.btc]
devnet = []
testnet = [
    { name = "publicnode-1", url = "https://bitcoin-testnet-rpc.publicnode.com" },
    { name = "publicnode-2", url = "https://bitcoin-testnet-rpc.publicnode.com" }
]
mainnet = [
    { name = "publicnode", url = "https://bitcoin-rpc.publicnode.com" }
]
